name: Wake NucLigs

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: |
          curl -L \
            --retry 5 \
            --retry-delay 20 \
            --connect-timeout 30 \
            --max-time 180 \
            -A "Mozilla/5.0" \
            https://nucligs.streamlit.app/ || true
